"""
main.py — INFO 588 Capstone
FastAPI layer on top of the funding_opportunities PostgreSQL database.

Pipeline position:
    Scraper -> JSON -> load.py -> PostgreSQL -> main.py -> Sponsor's team

Usage:
    uvicorn main:app --reload

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs

Endpoints:
    GET /                        health check
    GET /programs                all programs (paginated, filterable)
    GET /programs/non-dilutive   no fees, no equity, no SAFE notes
    GET /programs/{id}           single program + all child table data
    GET /summary                 counts by type, state, flagged status

Auth:
    All endpoints require header:  X-API-Key: <key>
    Key is set via API_KEY in your .env file.
"""

from contextlib import contextmanager
from typing import Optional

import os
import psycopg2
import psycopg2.extras
from dotenv import load_dotenv
from fastapi import Depends, FastAPI, Header, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

# Load .env from same directory as this file (or system environment variables)
load_dotenv()

DB_CONFIG = {
    "host":     os.getenv("PG_HOST",     "localhost"),
    "port":     int(os.getenv("PG_PORT", "5432")),
    "database": os.getenv("PG_DB",       "funding_opportunities"),
    "user":     os.getenv("PG_USER",     "capstone_admin"),
    "password": os.getenv("PG_PASSWORD", "capstonepw"),
}

API_KEY = os.getenv("API_KEY", "maryland-funding-api-2026")

app = FastAPI(
    title="Maryland Funding Opportunities API",
    description=(
        "Read access to Maryland state funding programs. "
        "Requires X-API-Key header on all endpoints."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


def verify_api_key(x_api_key: str = Header(..., description="API key")):
    if x_api_key != API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API key")


@contextmanager
def get_db():
    conn = psycopg2.connect(**DB_CONFIG)
    cur  = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        yield cur
    finally:
        cur.close()
        conn.close()


def fetch_children(cur, table: str, column: str, opportunity_id: int) -> list:
    cur.execute(
        f"SELECT {column} FROM {table} WHERE opportunity_id = %s ORDER BY id",
        (opportunity_id,)
    )
    return [row[column] for row in cur.fetchall()]


def fetch_award_amounts(cur, opportunity_id: int) -> list:
    cur.execute(
        "SELECT amount, context FROM award_amounts WHERE opportunity_id = %s ORDER BY id",
        (opportunity_id,)
    )
    return [dict(row) for row in cur.fetchall()]


@app.get("/", tags=["Health"])
def health_check():
    """Confirms the API is running. No auth required."""
    return {
        "status":  "ok",
        "api":     "Maryland Funding Opportunities",
        "version": "1.0.0",
        "docs":    "/docs",
    }


@app.get("/programs", tags=["Programs"])
def list_programs(
    opportunity_type: str           = Query(None, description="Filter by type: Grant, Loan, Tax Credit, etc."),
    state:            str           = Query(None, description="Filter by state"),
    rolling:          str           = Query(None, description="Filter by rolling deadline: Yes or No"),
    needs_review:     Optional[bool] = Query(None, description="true = flagged only | false = clean only"),
    active_only:      Optional[bool] = Query(None, description="true = exclude programs with past deadlines"),
    limit:            int           = Query(20, ge=1, le=100, description="Records per page (max 100)"),
    offset:           int           = Query(0,  ge=0,         description="Pagination offset"),
    _auth=Depends(verify_api_key),
):
    """
    Returns all programs with lightweight fields for browsing.
    Use /programs/{id} for full detail including child table data.

    active_only=true: excludes programs whose deadline has passed.
    Rolling and unspecified deadlines are always included.
    """
    conditions = []
    params     = []

    if opportunity_type is not None:
        conditions.append("opportunity_type ILIKE %s")
        params.append(f"%{opportunity_type}%")
    if state is not None:
        conditions.append("state ILIKE %s")
        params.append(f"%{state}%")
    if rolling is not None:
        conditions.append("rolling = %s")
        params.append(rolling)
    if needs_review is not None:
        conditions.append("needs_review = %s")
        params.append(needs_review)
    if active_only:
        conditions.append(
            "(deadline = 'Rolling'"
            " OR deadline = 'Not specified'"
            " OR (deadline ~ '^\\d{2}-\\d{2}-\\d{4}$'"
            "     AND TO_DATE(deadline, 'MM-DD-YYYY') >= CURRENT_DATE))"
        )

    where        = ("WHERE " + " AND ".join(conditions)) if conditions else ""
    count_params = params[:]
    list_params  = params + [limit, offset]

    with get_db() as cur:
        cur.execute(f"SELECT COUNT(*) AS total FROM opportunities {where}", count_params)
        total = cur.fetchone()["total"]

        cur.execute(f"""
            SELECT
                id, title, opportunity_type, award_value, deadline, rolling,
                sponsor, state, location, industry,
                needs_review, review_reason, scraped_at
            FROM opportunities
            {where}
            ORDER BY title
            LIMIT %s OFFSET %s
        """, list_params)
        rows = [dict(r) for r in cur.fetchall()]

    return {
        "total":   total,
        "limit":   limit,
        "offset":  offset,
        "results": rows,
    }


@app.get("/programs/non-dilutive", tags=["Programs"])
def non_dilutive_programs(
    limit:  int = Query(20, ge=1, le=100),
    offset: int = Query(0,  ge=0),
    _auth=Depends(verify_api_key),
):
    """
    Returns programs with no fees, no equity, and no SAFE notes.
    """
    with get_db() as cur:
        cur.execute("""
            SELECT COUNT(*) AS total FROM opportunities
            WHERE fee_required = 'No' AND equity_percentage = 'No' AND safe_note = 'No'
        """)
        total = cur.fetchone()["total"]

        cur.execute("""
            SELECT
                id, title, opportunity_type, award_value, deadline, rolling,
                sponsor, state, location, industry, needs_review
            FROM opportunities
            WHERE fee_required      = 'No'
              AND equity_percentage = 'No'
              AND safe_note         = 'No'
            ORDER BY title
            LIMIT %s OFFSET %s
        """, (limit, offset))
        rows = [dict(r) for r in cur.fetchall()]

    return {"total": total, "limit": limit, "offset": offset, "results": rows}


@app.get("/programs/{program_id}", tags=["Programs"])
def get_program(program_id: int, _auth=Depends(verify_api_key)):
    """
    Returns one program's full record including all child table data:
    award_amounts, tags, eligibility, areas_of_focus, sdg_alignments.
    """
    with get_db() as cur:
        cur.execute("SELECT * FROM opportunities WHERE id = %s", (program_id,))
        row = cur.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail=f"Program {program_id} not found")

        program = dict(row)
        oid     = program["id"]

        program["award_amounts"]  = fetch_award_amounts(cur, oid)
        program["tags"]           = fetch_children(cur, "tags",                 "tag",       oid)
        program["eligibility"]    = fetch_children(cur, "eligibility_criteria", "criterion", oid)
        program["areas_of_focus"] = fetch_children(cur, "areas_of_focus",       "area",      oid)
        program["sdg_alignments"] = fetch_children(cur, "sdg_alignments",       "sdg_tag",   oid)

    return program


@app.get("/summary", tags=["Analytics"])
def summary(_auth=Depends(verify_api_key)):
    """
    Returns aggregate counts useful for dashboards and reporting.
    """
    with get_db() as cur:
        cur.execute("SELECT COUNT(*) AS total FROM opportunities")
        total = cur.fetchone()["total"]

        cur.execute("SELECT COUNT(*) AS n FROM opportunities WHERE needs_review = TRUE")
        flagged = cur.fetchone()["n"]

        cur.execute("""
            SELECT opportunity_type, COUNT(*) AS count
            FROM opportunities
            GROUP BY opportunity_type
            ORDER BY count DESC
        """)
        by_type = [dict(r) for r in cur.fetchall()]

        cur.execute("""
            SELECT state, COUNT(*) AS count
            FROM opportunities
            GROUP BY state
            ORDER BY count DESC
        """)
        by_state = [dict(r) for r in cur.fetchall()]

        cur.execute("""
            SELECT rolling, COUNT(*) AS count
            FROM opportunities
            GROUP BY rolling
        """)
        by_rolling = [dict(r) for r in cur.fetchall()]

        cur.execute("""
            SELECT
                fee_required      = 'No' AND
                equity_percentage = 'No' AND
                safe_note         = 'No' AS non_dilutive,
                COUNT(*) AS count
            FROM opportunities
            GROUP BY non_dilutive
        """)
        dilutive_rows = cur.fetchall()
        non_dilutive_count = next(
            (r["count"] for r in dilutive_rows if r["non_dilutive"]), 0
        )

    return {
        "total":        total,
        "clean":        total - flagged,
        "flagged":      flagged,
        "non_dilutive": non_dilutive_count,
        "by_type":      by_type,
        "by_state":     by_state,
        "by_rolling":   by_rolling,
    }
